### ISSUE TITLE
User Story: implement high score functionality

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/2408-hackathon-team5#27]
As a **user** I can **see my high scores** so that I can **keep coming back for more**.

**Acceptance Criteria**
- [ ] score saved during gameplay.
- [x] high scores displayed on highscores.html page.

**Tasks**
- [ ] implement code for saving scores during gameplay.
- [x] implement code for getting and displaying scores.
