### ISSUE TITLE
User Story: create race car

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/2408-hackathon-team5#3]
As a **user** I can **see my car** so that I can **play an awesome game**.

**Acceptance Criteria**
- [x] Car is visible when game loads.
- [x] Car moves with user inputs.

**Tasks**
- [x] Code car in JavaScript.
- [x] Use translation and rotation matrices to move the cars.
