### ISSUE TITLE
User Story: navigate between pages

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/2408-hackathon-team5#5]
As a **user** I can **navigate between pages** so that I can **navigate to game, settings and high scores**.

**Acceptance Criteria**
- [x] Home screen provides links to game, settings and high scores

**Tasks**
- [ ] Design nav layout in Lucidchart
- [x] Choose colour palette and fonts based on online retro games
- [x] Code HTML.
