### ISSUE TITLE
User Story: enhanced car features

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/2408-hackathon-team5#8]
As a **racer** I can **use enhanced car features** so that I can **play a fun game**.

**Acceptance Criteria**
- [ ] The project is fun to play
- [ ] Score saved to `LocalStorage`
- [ ] Car colour set in settings.
- [ ] Difficulty set in settings.

**Tasks**
- [ ] Code race finish after 5 laps and save score to `LocalStorage`
- [ ] Code interaction with other cars
- [ ] Code banana skin
- [ ] Code magnetism
- [ ] Code car colour in settings.
- [ ] Code difficulty in settings.
