### ISSUE TITLE
User Story: enhanced track features

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/2408-hackathon-team5#9]
As a **racer** I can **use enhanced track features** so that I can **play a fun game**.

**Acceptance Criteria**
- [x] The project is fun to play
- [ ] Car has 'sticky movement' if it moves off track

**Tasks**
- [x] Code panning plan view
- [ ] Code 'sticky movement' if car moves off track
